namespace RecreioBarcode.Application.UseCase.Inventories.Queries.ListLinesByInventoryLocation;

public sealed record ListInventoryLinesByInventoryLocationQuery(int InventoryId, int InventoryLocationId);