// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecreioBarcodeApi.Context;

#nullable disable

namespace RecreioBarcodeApi.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20251231010901_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecreioBarcodeApi.Entities.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChargeArchivePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("RecreioBarcodeApi.Entities.InventoryItemOut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountedQuantity")
                        .HasColumnType("int");

                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationFoundId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.HasIndex("LocationFoundId");

                    b.HasIndex("UserId");

                    b.ToTable("InventoryItemsOut");
                });

            modelBuilder.Entity("RecreioBarcodeApi.Entities.InventoryLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountedQuantity")
                        .HasColumnType("int");

                    b.Property<int>("InventoryLocationId")
                        .HasColumnType("int");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryLocationId");

                    b.ToTable("InventoryLines");
                });

            modelBuilder.Entity("RecreioBarcodeApi.Entities.InventoryLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("InventoriedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsInventoried")
                        .HasColumnType("bit");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.HasIndex("LocationId");

                    b.HasIndex("UserId");

                    b.ToTable("InventoryLocations");
                });

            modelBuilder.Entity("RecreioBarcodeApi.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estante")
                        .HasColumnType("int");

                    b.Property<string>("Prateleira")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("Rua")
                        .HasColumnType("int");

                    b.Property<string>("Zona")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("numero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("RecreioBarcodeApi.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RecreioBarcodeApi.Entities.InventoryItemOut", b =>
                {
                    b.HasOne("RecreioBarcodeApi.Entities.Inventory", "Inventory")
                        .WithMany("InventoryItemsOut")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecreioBarcodeApi.Entities.Location", "LocationFound")
                        .WithMany("InventoryItemsOut")
                        .HasForeignKey("LocationFoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecreioBarcodeApi.Entities.User", "User")
                        .WithMany("InventoryItemsOut")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("LocationFound");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecreioBarcodeApi.Entities.InventoryLine", b =>
                {
                    b.HasOne("RecreioBarcodeApi.Entities.InventoryLocation", "Location")
                        .WithMany("InventoryLines")
                        .HasForeignKey("InventoryLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("RecreioBarcodeApi.Entities.InventoryLocation", b =>
                {
                    b.HasOne("RecreioBarcodeApi.Entities.Inventory", "Inventory")
                        .WithMany("InventoryLocations")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecreioBarcodeApi.Entities.Location", "Location")
                        .WithMany("InventoryLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecreioBarcodeApi.Entities.User", "User")
                        .WithMany("InventoryLocations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecreioBarcodeApi.Entities.Inventory", b =>
                {
                    b.Navigation("InventoryItemsOut");

                    b.Navigation("InventoryLocations");
                });

            modelBuilder.Entity("RecreioBarcodeApi.Entities.InventoryLocation", b =>
                {
                    b.Navigation("InventoryLines");
                });

            modelBuilder.Entity("RecreioBarcodeApi.Entities.Location", b =>
                {
                    b.Navigation("InventoryItemsOut");

                    b.Navigation("InventoryLocations");
                });

            modelBuilder.Entity("RecreioBarcodeApi.Entities.User", b =>
                {
                    b.Navigation("InventoryItemsOut");

                    b.Navigation("InventoryLocations");
                });
#pragma warning restore 612, 618
        }
    }
}
