// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecreioBarcode.Infra.Data.Context;

#nullable disable

namespace RecreioBarcode.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260122130811_contadores")]
    partial class contadores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecreioBarcode.Domain.Entities.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TotalInventoriedLocations")
                        .HasColumnType("int");

                    b.Property<int>("TotalItemsOut")
                        .HasColumnType("int");

                    b.Property<int>("TotalLines")
                        .HasColumnType("int");

                    b.Property<int>("TotalLocations")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Inventories", null, t =>
                        {
                            t.HasCheckConstraint("CK_Inventories_ActiveOpen", "(IsActive = 1) OR (IsActive = 0 AND IsOpen = 0)");

                            t.HasCheckConstraint("Ck_Inventory_FinishedAt", "(IsActive = 1 AND FinishedAt IS NULL) OR (IsActive = 0 AND FinishedAt IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("RecreioBarcode.Domain.Entities.InventoryItemOut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Count")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(1m);

                    b.Property<int>("FoundLocationId")
                        .HasColumnType("int");

                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.HasKey("Id");

                    b.HasIndex("FoundLocationId");

                    b.HasIndex("InventoryId");

                    b.ToTable("InventoryItemsOut", (string)null);
                });

            modelBuilder.Entity("RecreioBarcode.Domain.Entities.InventoryLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("InventoryLocationId")
                        .HasColumnType("int");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryLocationId", "ItemCode")
                        .IsUnique()
                        .HasDatabaseName("UX_InventoryLines_InventoryLocation_ItemCode");

                    b.ToTable("InventoryLines", (string)null);
                });

            modelBuilder.Entity("RecreioBarcode.Domain.Entities.InventoryLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("InventoriedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsInventoried")
                        .HasColumnType("bit");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("TotalLines")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("InventoryId", "LocationId")
                        .IsUnique()
                        .HasDatabaseName("UX_InventoryLocation_Inventory_Location");

                    b.ToTable("InventoryLocations", null, t =>
                        {
                            t.HasCheckConstraint("CK_InventoryLocations_InventoriedAt", "(IsInventoried = 0 AND InventoriedAt IS NULL) OR (IsInventoried = 1 AND InventoriedAt IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("RecreioBarcode.Domain.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estante")
                        .HasColumnType("int");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Prateleira")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("Rua")
                        .HasColumnType("int");

                    b.Property<string>("Zona")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("Zona", "Rua", "Estante", "Prateleira", "Numero")
                        .IsUnique()
                        .HasDatabaseName("UX_Location_Zona_Rua_Estante_Prateleira_numero");

                    b.ToTable("Locations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Locations_Estante", "Estante BETWEEN 1 AND 999");

                            t.HasCheckConstraint("CK_Locations_Numero", "Numero BETWEEN 1 AND 999");

                            t.HasCheckConstraint("CK_Locations_Rua", "Rua BETWEEN 1 AND 99");
                        });
                });

            modelBuilder.Entity("RecreioBarcode.Domain.Entities.InventoryItemOut", b =>
                {
                    b.HasOne("RecreioBarcode.Domain.Entities.InventoryLocation", "FoundLocation")
                        .WithMany()
                        .HasForeignKey("FoundLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RecreioBarcode.Domain.Entities.Inventory", "Inventory")
                        .WithMany("InventoryItemsOut")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoundLocation");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("RecreioBarcode.Domain.Entities.InventoryLine", b =>
                {
                    b.HasOne("RecreioBarcode.Domain.Entities.InventoryLocation", "InventoryLocation")
                        .WithMany("InventoryLines")
                        .HasForeignKey("InventoryLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryLocation");
                });

            modelBuilder.Entity("RecreioBarcode.Domain.Entities.InventoryLocation", b =>
                {
                    b.HasOne("RecreioBarcode.Domain.Entities.Inventory", "Inventory")
                        .WithMany("InventoryLocations")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecreioBarcode.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("RecreioBarcode.Domain.Entities.Inventory", b =>
                {
                    b.Navigation("InventoryItemsOut");

                    b.Navigation("InventoryLocations");
                });

            modelBuilder.Entity("RecreioBarcode.Domain.Entities.InventoryLocation", b =>
                {
                    b.Navigation("InventoryLines");
                });
#pragma warning restore 612, 618
        }
    }
}
