// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecreioBarcode.Infra.Data.Context;

#nullable disable

namespace RecreioBarcode.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260112230510_TerceiraMigration")]
    partial class TerceiraMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecreioBarcode.Domain.Entities.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("ItStarted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 6, 14, 59, 25, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ItStarted = false,
                            Name = "Inventário Teste"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 6, 14, 59, 25, 0, DateTimeKind.Utc),
                            FinishedAt = new DateTime(2026, 1, 6, 14, 59, 25, 0, DateTimeKind.Utc),
                            IsActive = false,
                            ItStarted = false,
                            Name = "Inventário Teste 2"
                        });
                });

            modelBuilder.Entity("RecreioBarcode.Domain.Entities.InventoryItemOut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.HasIndex("LocationId");

                    b.HasIndex("UserId");

                    b.ToTable("InventoryItemsOut");
                });

            modelBuilder.Entity("RecreioBarcode.Domain.Entities.InventoryLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("InventoryLocationId")
                        .HasColumnType("int");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryLocationId");

                    b.ToTable("InventoryLines");
                });

            modelBuilder.Entity("RecreioBarcode.Domain.Entities.InventoryLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("InventoriedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsInventoried")
                        .HasColumnType("bit");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.HasIndex("LocationId");

                    b.HasIndex("UserId");

                    b.ToTable("InventoryLocations");
                });

            modelBuilder.Entity("RecreioBarcode.Domain.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estante")
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Prateleira")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("Rua")
                        .HasColumnType("int");

                    b.Property<string>("Zona")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estante = 1,
                            Numero = 1,
                            Prateleira = "A",
                            Rua = 1,
                            Zona = "A"
                        },
                        new
                        {
                            Id = 2,
                            Estante = 99,
                            Numero = 1,
                            Prateleira = "B",
                            Rua = 2,
                            Zona = "A"
                        },
                        new
                        {
                            Id = 3,
                            Estante = 99,
                            Numero = 1,
                            Prateleira = "C",
                            Rua = 1,
                            Zona = "B"
                        },
                        new
                        {
                            Id = 4,
                            Estante = 99,
                            Numero = 2,
                            Prateleira = "D",
                            Rua = 2,
                            Zona = "B"
                        },
                        new
                        {
                            Id = 5,
                            Estante = 99,
                            Numero = 99,
                            Prateleira = "Z",
                            Rua = 99,
                            Zona = "Z"
                        });
                });

            modelBuilder.Entity("RecreioBarcode.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IpAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IpAdress = "",
                            Name = "Thiago"
                        },
                        new
                        {
                            Id = 2,
                            IpAdress = "",
                            Name = "Pedro"
                        },
                        new
                        {
                            Id = 3,
                            IpAdress = "",
                            Name = "Franklin"
                        });
                });

            modelBuilder.Entity("RecreioBarcode.Domain.Entities.InventoryItemOut", b =>
                {
                    b.HasOne("RecreioBarcode.Domain.Entities.Inventory", "Inventory")
                        .WithMany("InventoryItemsOut")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecreioBarcode.Domain.Entities.Location", "Location")
                        .WithMany("InventoryItemsOut")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecreioBarcode.Domain.Entities.User", "User")
                        .WithMany("InventoryItemsOut")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecreioBarcode.Domain.Entities.InventoryLine", b =>
                {
                    b.HasOne("RecreioBarcode.Domain.Entities.InventoryLocation", "InventoryLocation")
                        .WithMany("InventoryLines")
                        .HasForeignKey("InventoryLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryLocation");
                });

            modelBuilder.Entity("RecreioBarcode.Domain.Entities.InventoryLocation", b =>
                {
                    b.HasOne("RecreioBarcode.Domain.Entities.Inventory", "Inventory")
                        .WithMany("InventoryLocations")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecreioBarcode.Domain.Entities.Location", "Location")
                        .WithMany("InventoryLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecreioBarcode.Domain.Entities.User", "User")
                        .WithMany("InventoryLocations")
                        .HasForeignKey("UserId");

                    b.Navigation("Inventory");

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecreioBarcode.Domain.Entities.Inventory", b =>
                {
                    b.Navigation("InventoryItemsOut");

                    b.Navigation("InventoryLocations");
                });

            modelBuilder.Entity("RecreioBarcode.Domain.Entities.InventoryLocation", b =>
                {
                    b.Navigation("InventoryLines");
                });

            modelBuilder.Entity("RecreioBarcode.Domain.Entities.Location", b =>
                {
                    b.Navigation("InventoryItemsOut");

                    b.Navigation("InventoryLocations");
                });

            modelBuilder.Entity("RecreioBarcode.Domain.Entities.User", b =>
                {
                    b.Navigation("InventoryItemsOut");

                    b.Navigation("InventoryLocations");
                });
#pragma warning restore 612, 618
        }
    }
}
